server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7000/eureka



spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationFilter

        - id: article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=article-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/article-service/(?<segment>.*), /$\{segment}
            - AuthorizationFilter


        - id: room-service
          uri: lb//ROOM-SERVICE
          predicates:
            - Path=room-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/room-service/(?<segment>.*), /$\{segment}
            - AuthorizationFilter



